Starting pur_porringer as ubuntu
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
Starting pur_porringer as ubuntu
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
Starting pur_porringer as ubuntu
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
Starting pur_porringer as ubuntu
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
global name 'reverse' is not defined
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
global name 'reverse' is not defined
Starting pur_porringer as ubuntu
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
global name 'reverse' is not defined
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
global name 'reverse' is not defined
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
global name 'reverse' is not defined
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
global name 'reverse' is not defined
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
global name 'reverse' is not defined
Error reading SSH protocol banner
Error reading SSH protocol banner
Error reading SSH protocol banner
Error reading SSH protocol banner
Error reading SSH protocol banner
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
global name 'reverse' is not defined
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
global name 'reverse' is not defined
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
global name 'reverse' is not defined
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
global name 'reverse' is not defined
Error reading SSH protocol banner
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
global name 'reverse' is not defined
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
global name 'reverse' is not defined
debian-reference-common.desktop
hi
idle3.desktop
idle.desktop
lxterminal.desktop
midori.desktop
ocr_resources.desktop
pistore.desktop
python-games.desktop
scratch.desktop
shutdown.desktop
wolfram-language.desktop
wolfram-mathematica.desktop
wpa_gui.desktop
global name 'reverse' is not defined
Error reading SSH protocol banner
Starting pur_porringer as ubuntu
Error reading SSH protocol banner
Error reading SSH protocol banner
Starting pur_porringer as ubuntu
Error reading SSH protocol banner
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
global name 'reverse' is not defined
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
Starting pur_porringer as ubuntu
global name 'reverse' is not defined
global name 'reverse' is not defined
Starting pur_porringer as ubuntu
global name 'reverse' is not defined
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
Error reading SSH protocol banner
Error reading SSH protocol banner
Error reading SSH protocol banner
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
Error reading SSH protocol banner
Error reading SSH protocol banner
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
Error reading SSH protocol banner
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
Starting pur_porringer as ubuntu
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
[Errno None] Unable to connect to port 2222 on  or 127.0.0.1
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
Traceback (most recent call last):
  File "/opt/envs/pur_porringer/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 189, in run
    super(Application, self).run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 201, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 297, in halt
    self.stop()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 342, in stop
    time.sleep(0.1)
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 214, in handle_chld
    self.reap_workers()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Starting pur_porringer as ubuntu
Traceback (most recent call last):
  File "/opt/envs/pur_porringer/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 189, in run
    super(Application, self).run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 201, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 297, in halt
    self.stop()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 342, in stop
    time.sleep(0.1)
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 214, in handle_chld
    self.reap_workers()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Starting pur_porringer as ubuntu
Traceback (most recent call last):
  File "/opt/envs/pur_porringer/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 189, in run
    super(Application, self).run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 201, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 297, in halt
    self.stop()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 342, in stop
    time.sleep(0.1)
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 214, in handle_chld
    self.reap_workers()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Starting pur_porringer as ubuntu
Traceback (most recent call last):
  File "/opt/envs/pur_porringer/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 189, in run
    super(Application, self).run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 201, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 297, in halt
    self.stop()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 342, in stop
    time.sleep(0.1)
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 214, in handle_chld
    self.reap_workers()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Starting pur_porringer as ubuntu
Traceback (most recent call last):
  File "/opt/envs/pur_porringer/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 189, in run
    super(Application, self).run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 174, in run
    self.manage_workers()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 477, in manage_workers
    self.spawn_workers()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 541, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 214, in handle_chld
    self.reap_workers()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Starting pur_porringer as ubuntu
Traceback (most recent call last):
  File "/opt/envs/pur_porringer/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 189, in run
    super(Application, self).run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 201, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 297, in halt
    self.stop()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 342, in stop
    time.sleep(0.1)
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 214, in handle_chld
    self.reap_workers()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Starting pur_porringer as ubuntu
Traceback (most recent call last):
  File "/opt/envs/pur_porringer/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 189, in run
    super(Application, self).run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 201, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 297, in halt
    self.stop()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 342, in stop
    time.sleep(0.1)
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 214, in handle_chld
    self.reap_workers()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Starting pur_porringer as ubuntu
Traceback (most recent call last):
  File "/opt/envs/pur_porringer/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 189, in run
    super(Application, self).run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 201, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 297, in halt
    self.stop()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 342, in stop
    time.sleep(0.1)
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 214, in handle_chld
    self.reap_workers()
  File "/opt/envs/pur_porringer/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Starting pur_porringer as ubuntu
Starting pur_porringer as ubuntu
